export const facilityLocations = [
  {
    key: "post",
    label: "Post",
    images: {
      desktop: [
        "/assets/images/home/facility/post5.webp",
        "/assets/images/home/facility/post10.webp",
        "/assets/images/home/facility/post7.webp",
        "/assets/images/home/facility/post2.webp",
        "/assets/images/home/facility/post1.webp",
        "/assets/images/home/facility/post3.webp",
        "/assets/images/home/facility/post9.webp",
        "/assets/images/home/facility/post6.webp",
        "/assets/images/home/facility/post4.webp",
      ],
      mobile: [
        "/assets/images/home/facility/post5Mob.webp",
        "/assets/images/home/facility/post10Mob.webp",
        "/assets/images/home/facility/post7Mob.webp",
        "/assets/images/home/facility/post2Mob.webp",
        "/assets/images/home/facility/post1Mob.webp",
        "/assets/images/home/facility/post3Mob.webp",
        "/assets/images/home/facility/post9Mob.webp",
        "/assets/images/home/facility/post6Mob.webp",
        "/assets/images/home/facility/post4Mob.webp",
      ],
    },
  },
  {
    key: "brentwood",
    label: "Brentwood",
    images: {
      desktop: [
        "/assets/images/home/facility/brentwood11.webp",
        "/assets/images/home/facility/brentwood2.webp",
        "/assets/images/home/facility/brentwood3.webp",
        "/assets/images/home/facility/brentwood4.webp",
        "/assets/images/home/facility/brentwood5.webp",
        "/assets/images/home/facility/brentwood10.webp",
        "/assets/images/home/facility/brentwood7.webp",
        "/assets/images/home/facility/brentwood8.webp",
        "/assets/images/home/facility/brentwood9.webp",
      ],
      mobile: [
        "/assets/images/home/facility/brentwood1Mob.webp",
        "/assets/images/home/facility/brentwood2Mob.webp",
        "/assets/images/home/facility/brentwood3Mob.webp",
        "/assets/images/home/facility/brentwood4Mob.webp",
        "/assets/images/home/facility/brentwood5Mob.webp",
        "/assets/images/home/facility/brentwood10Mob.webp",
        "/assets/images/home/facility/brentwood7Mob.webp",
        "/assets/images/home/facility/brentwood8Mob.webp",
        "/assets/images/home/facility/downtown_mob_9.webp",
      ],
    },
  },
  {
    key: "seton",
    label: "Seton",
    images: {
      desktop: [
        "/assets/images/home/facility/seton1.webp",
        "/assets/images/home/facility/seton2.webp",
        "/assets/images/home/facility/seton3.webp",
        "/assets/images/home/facility/seton4.webp",
        "/assets/images/home/facility/seton5.webp",
        "/assets/images/home/facility/seton6.webp",
        "/assets/images/home/facility/seton7.webp",
        "/assets/images/home/facility/seton8.webp",
        "/assets/images/home/facility/seton9.webp",
      ],
      mobile: [
        "/assets/images/home/facility/seton1Mob.webp",
        "/assets/images/home/facility/seton2Mob.webp",
        "/assets/images/home/facility/seton3Mob.webp",
        "/assets/images/home/facility/seton4Mob.webp",
        "/assets/images/home/facility/seton5Mob.webp",
        "/assets/images/home/facility/seton6Mob.webp",
        "/assets/images/home/facility/seton7Mob.webp",
        "/assets/images/home/facility/seton8Mob.webp",
        "/assets/images/home/facility/seton9Mob.webp",
      ],
    },
  },
  {
    key: "royaloak",
    label: "Royal Oak",
    images: {
      desktop: [
        "/assets/images/home/facility/royal_oak_1.webp",
        "/assets/images/home/facility/royal_oak_2.webp",
        "/assets/images/home/facility/royal_oak_3.webp",
        "/assets/images/home/facility/royal_oak_4.webp",
        "/assets/images/home/facility/royal_oak_5.webp",
        "/assets/images/home/facility/royal_oak_6.webp",
        "/assets/images/home/facility/royal_oak_7.webp",
        "/assets/images/home/facility/royal_oak_8.webp",
      ],
      mobile: [
        "/assets/images/home/facility/royal_oak_1Mob.webp",
        "/assets/images/home/facility/royal_oak_2Mob.webp",
        "/assets/images/home/facility/royal_oak_3Mob.webp",
        "/assets/images/home/facility/royal_oak_4Mob.webp",
        "/assets/images/home/facility/royal_oak_5Mob.webp",
        "/assets/images/home/facility/royal_oak_6Mob.webp",
        "/assets/images/home/facility/royal_oak_7Mob.webp",
        "/assets/images/home/facility/royal_oak_8Mob.webp",
      ],
    },
  },
  // {
  //   key: "sunridge",
  //   label: "Sunridge",
  //   images: {
  //     desktop: [
  //       "/assets/images/home/facility/sunridge1.webp",
  //       "/assets/images/home/facility/sunridge2.webp",
  //       "/assets/images/home/facility/sunridge3.webp",
  //       "/assets/images/home/facility/sunridge4.webp",
  //       "/assets/images/home/facility/sunridge5.webp",
  //       "/assets/images/home/facility/sunridge6.webp",
  //       "/assets/images/home/facility/sunridge7.webp",
  //       "/assets/images/home/facility/sunridge8.webp",
  //       "/assets/images/home/facility/sunridge9.webp",
  //     ],
  //     mobile: [
  //       "/assets/images/home/facility/sunridge1Mob.webp",
  //       "/assets/images/home/facility/sunridge2Mob.webp",
  //       "/assets/images/home/facility/sunridge3Mob.webp",
  //       "/assets/images/home/facility/sunridge4Mob.webp",
  //       "/assets/images/home/facility/sunridge5Mob.webp",
  //       "/assets/images/home/facility/sunridge6Mob.webp",
  //       "/assets/images/home/facility/sunridge7Mob.webp",
  //       "/assets/images/home/facility/sunridge8Mob.webp",
  //       "/assets/images/home/facility/sunridge9Mob.webp",
  //     ],
  //   },
  // },
  {
    key: "downtown",
    label: "Downtown",
    images: {
      desktop: [
        "https://tor1.digitaloceanspaces.com/evolve-strength/assets/images/home/facility/downtown_9.webp.webp",
        "/assets/images/home/facility/downtown_1.webp",
        "/assets/images/home/facility/downtown_3.webp",
        "/assets/images/home/facility/downtown_2.webp",
        "/assets/images/home/facility/downtown_4.webp",
        "/assets/images/home/facility/downtown_5.webp",
        "/assets/images/home/facility/downtown_6.webp",
        "/assets/images/home/facility/downtown_7.webp",
        "/assets/images/home/facility/downtown_8.webp",
      ],
      mobile: [
        "https://tor1.digitaloceanspaces.com/evolve-strength/assets/images/home/facility/downtown_9.webp.webp",
        "/assets/images/home/facility/downtown_1Mob.webp",
        "/assets/images/home/facility/downtown_2Mob.webp",
        "/assets/images/home/facility/downtown_3Mob.webp",
        "/assets/images/home/facility/downtown_4Mob.webp",
        "/assets/images/home/facility/downtown_5Mob.webp",
        "/assets/images/home/facility/downtown_6Mob.webp",
        "/assets/images/home/facility/downtown_7Mob.webp",
        "/assets/images/home/facility/downtown_8Mob.webp",
      ],
    },
  },
  {
    key: "north",
    label: "North",
    images: {
      desktop: [
        "/assets/images/home/facility/north1.webp",
        "/assets/images/home/facility/north2.webp",
        "/assets/images/home/facility/north3.webp",
        "/assets/images/home/facility/north4.webp",
        "/assets/images/home/facility/north5.webp",
        "/assets/images/home/facility/north6.webp",
        "/assets/images/home/facility/north7.webp",
        "/assets/images/home/facility/north8.webp",
      ],
      mobile: [
        "/assets/images/home/facility/north1Mob.webp",
        "/assets/images/home/facility/north2Mob.webp",
        "/assets/images/home/facility/north3Mob.webp",
        "/assets/images/home/facility/north4Mob.webp",
        "/assets/images/home/facility/north5Mob.webp",
        "/assets/images/home/facility/north6Mob.webp",
        "/assets/images/home/facility/north7Mob.webp",
        "/assets/images/home/facility/north8Mob.webp",
      ],
    },
  },
  {
    key: "south",
    label: "South",
    images: {
      desktop: [
        "/assets/images/home/facility/south_8.webp",
        "/assets/images/home/facility/south_2.webp",
        "/assets/images/home/facility/south_3.webp",
        "/assets/images/home/facility/south_4.webp",
        "/assets/images/home/facility/south_5.webp",
        "/assets/images/home/facility/south_6.webp",
        "/assets/images/home/facility/south_7.webp",
        "/assets/images/home/facility/south_1.webp",
        "/assets/images/home/facility/south_9.webp",
      ],
      mobile: [
        "/assets/images/home/facility/south_8Mob.webp",
        "/assets/images/home/facility/south_2Mob.webp",
        "/assets/images/home/facility/south_3Mob.webp",
        "/assets/images/home/facility/south_4Mob.webp",
        "/assets/images/home/facility/south_10Mob.webp",
        "/assets/images/home/facility/south_6Mob.webp",
        "/assets/images/home/facility/south_7Mob.webp",
        "/assets/images/home/facility/south_1Mob.webp",
        "/assets/images/home/facility/south_9Mob.webp",
      ],
    },
  },
];

export const getImagesForDevice = (locationKey, deviceType = "desktop") => {
  const location = facilityLocations.find((loc) => loc.key === locationKey);
  return location ? location.images[deviceType] : [];
};

export const getLocationData = (locationKey) => {
  return facilityLocations.find((loc) => loc.key === locationKey);
};
