import { assetUrl } from "@/lib/assetUrl";
export const facilityLocations = [
  {
    key: "post",
    label: "Post",
    images: {
      desktop: [
        assetUrl("/assets/images/home/facility/post5.webp"),
        assetUrl("/assets/images/home/facility/post10.webp"),
        assetUrl("/assets/images/home/facility/post7.webp"),
        assetUrl("/assets/images/home/facility/post2.webp"),
        assetUrl("/assets/images/home/facility/post1.webp"),
        assetUrl("/assets/images/home/facility/post3.webp"),
        assetUrl("/assets/images/home/facility/post9.webp"),
        assetUrl("/assets/images/home/facility/post6.webp"),
        assetUrl("/assets/images/home/facility/post4.webp"),
      ],
      mobile: [
        assetUrl("/assets/images/home/facility/post5Mob.webp"),
        assetUrl("/assets/images/home/facility/post10Mob.webp"),
        assetUrl("/assets/images/home/facility/post7Mob.webp"),
        assetUrl("/assets/images/home/facility/post2Mob.webp"),
        assetUrl("/assets/images/home/facility/post1Mob.webp"),
        assetUrl("/assets/images/home/facility/post3Mob.webp"),
        assetUrl("/assets/images/home/facility/post9Mob.webp"),
        assetUrl("/assets/images/home/facility/post6Mob.webp"),
        assetUrl("/assets/images/home/facility/post4Mob.webp"),
      ],
    },
  },
  {
    key: "brentwood",
    label: "Brentwood",
    images: {
      desktop: [
        assetUrl("/assets/images/home/facility/brentwood11.webp"),
        assetUrl("/assets/images/home/facility/brentwood2.webp"),
        assetUrl("/assets/images/home/facility/brentwood3.webp"),
        assetUrl("/assets/images/home/facility/brentwood4.webp"),
        assetUrl("/assets/images/home/facility/brentwood5.webp"),
        assetUrl("/assets/images/home/facility/brentwood10.webp"),
        assetUrl("/assets/images/home/facility/brentwood7.webp"),
        assetUrl("/assets/images/home/facility/brentwood8.webp"),
        assetUrl("/assets/images/home/facility/brentwood9.webp"),
      ],
      mobile: [
        assetUrl("/assets/images/home/facility/brentwood1Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood2Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood3Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood4Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood5Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood10Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood7Mob.webp"),
        assetUrl("/assets/images/home/facility/brentwood8Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_mob_9.webp"),
      ],
    },
  },
  {
    key: "seton",
    label: "Seton",
    images: {
      desktop: [
        assetUrl("/assets/images/home/facility/seton1.webp"),
        assetUrl("/assets/images/home/facility/seton2.webp"),
        assetUrl("/assets/images/home/facility/seton3.webp"),
        assetUrl("/assets/images/home/facility/seton4.webp"),
        assetUrl("/assets/images/home/facility/seton5.webp"),
        assetUrl("/assets/images/home/facility/seton6.webp"),
        assetUrl("/assets/images/home/facility/seton7.webp"),
        assetUrl("/assets/images/home/facility/seton8.webp"),
        assetUrl("/assets/images/home/facility/seton9.webp"),
      ],
      mobile: [
        assetUrl("/assets/images/home/facility/seton1Mob.webp"),
        assetUrl("/assets/images/home/facility/seton2Mob.webp"),
        assetUrl("/assets/images/home/facility/seton3Mob.webp"),
        assetUrl("/assets/images/home/facility/seton4Mob.webp"),
        assetUrl("/assets/images/home/facility/seton5Mob.webp"),
        assetUrl("/assets/images/home/facility/seton6Mob.webp"),
        assetUrl("/assets/images/home/facility/seton7Mob.webp"),
        assetUrl("/assets/images/home/facility/seton8Mob.webp"),
        assetUrl("/assets/images/home/facility/seton9Mob.webp"),
      ],
    },
  },
  {
    key: "royaloak",
    label: "Royal Oak",
    images: {
      desktop: [
        assetUrl("/assets/images/home/facility/royal_oak_1.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_2.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_3.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_4.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_5.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_6.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_7.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_8.webp"),
      ],
      mobile: [
        assetUrl("/assets/images/home/facility/royal_oak_1Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_2Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_3Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_4Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_5Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_6Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_7Mob.webp"),
        assetUrl("/assets/images/home/facility/royal_oak_8Mob.webp"),
      ],
    },
  },
  // {
  //   key: "sunridge",
  //   label: "Sunridge",
  //   images: {
  //     desktop: [
  //       assetUrl("/assets/images/home/facility/sunridge1.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge2.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge3.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge4.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge5.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge6.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge7.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge8.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge9.webp"),
  //     ],
  //     mobile: [
  //       assetUrl("/assets/images/home/facility/sunridge1Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge2Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge3Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge4Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge5Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge6Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge7Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge8Mob.webp"),
  //       assetUrl("/assets/images/home/facility/sunridge9Mob.webp"),
  //     ],
  //   },
  // },
  {
    key: "downtown",
    label: "Downtown",
    images: {
      desktop: [
        "https://assets.evolvestrength.ca/assets/images/home/facility/downtown_9.webp.webp",
        assetUrl("/assets/images/home/facility/downtown_1.webp"),
        assetUrl("/assets/images/home/facility/downtown_3.webp"),
        assetUrl("/assets/images/home/facility/downtown_2.webp"),
        assetUrl("/assets/images/home/facility/downtown_4.webp"),
        assetUrl("/assets/images/home/facility/downtown_5.webp"),
        assetUrl("/assets/images/home/facility/downtown_6.webp"),
        assetUrl("/assets/images/home/facility/downtown_7.webp"),
        assetUrl("/assets/images/home/facility/downtown_8.webp"),
      ],
      mobile: [
        "https://assets.evolvestrength.ca/assets/images/home/facility/downtown_9.webp.webp",
        assetUrl("/assets/images/home/facility/downtown_1Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_2Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_3Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_4Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_5Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_6Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_7Mob.webp"),
        assetUrl("/assets/images/home/facility/downtown_8Mob.webp"),
      ],
    },
  },
  {
    key: "north",
    label: "North",
    images: {
      desktop: [
        assetUrl("/assets/images/home/facility/north1.webp"),
        assetUrl("/assets/images/home/facility/north2.webp"),
        assetUrl("/assets/images/home/facility/north3.webp"),
        assetUrl("/assets/images/home/facility/north4.webp"),
        assetUrl("/assets/images/home/facility/north5.webp"),
        assetUrl("/assets/images/home/facility/north6.webp"),
        assetUrl("/assets/images/home/facility/north7.webp"),
        assetUrl("/assets/images/home/facility/north8.webp"),
      ],
      mobile: [
        assetUrl("/assets/images/home/facility/north1Mob.webp"),
        assetUrl("/assets/images/home/facility/north2Mob.webp"),
        assetUrl("/assets/images/home/facility/north3Mob.webp"),
        assetUrl("/assets/images/home/facility/north4Mob.webp"),
        assetUrl("/assets/images/home/facility/north5Mob.webp"),
        assetUrl("/assets/images/home/facility/north6Mob.webp"),
        assetUrl("/assets/images/home/facility/north7Mob.webp"),
        assetUrl("/assets/images/home/facility/north8Mob.webp"),
      ],
    },
  },
  // {
  //   key: "south",
  //   label: "South",
  //   images: {
  //     desktop: [
  //       assetUrl("/assets/images/home/facility/south_8.webp"),
  //       assetUrl("/assets/images/home/facility/south_2.webp"),
  //       assetUrl("/assets/images/home/facility/south_3.webp"),
  //       assetUrl("/assets/images/home/facility/south_4.webp"),
  //       assetUrl("/assets/images/home/facility/south_5.webp"),
  //       assetUrl("/assets/images/home/facility/south_6.webp"),
  //       assetUrl("/assets/images/home/facility/south_7.webp"),
  //       assetUrl("/assets/images/home/facility/south_1.webp"),
  //       assetUrl("/assets/images/home/facility/south_9.webp"),
  //     ],
  //     mobile: [
  //       assetUrl("/assets/images/home/facility/south_8Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_2Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_3Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_4Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_10Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_6Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_7Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_1Mob.webp"),
  //       assetUrl("/assets/images/home/facility/south_9Mob.webp"),
  //     ],
  //   },
  // },
  {
    key: "south common",
    label: "South Commons",
    images: {
      desktop: [
        "https://assets.evolvestrength.ca/media/1770304404780-80b9f5db-508e-4f5a-9012-26fac72a4681.webp",
        "https://assets.evolvestrength.ca/media/1770305496673-9d5e6fef-a478-41eb-9abb-8a34058b41b7.webp",
        "https://assets.evolvestrength.ca/media/1770304391753-57bca423-49c1-40a6-9a25-9f3e25df5af8.webp",
      ],
      mobile: [
        "https://assets.evolvestrength.ca/media/1770304404780-80b9f5db-508e-4f5a-9012-26fac72a4681.webp",
        "https://assets.evolvestrength.ca/media/1770305496673-9d5e6fef-a478-41eb-9abb-8a34058b41b7.webp",
        "https://assets.evolvestrength.ca/media/1770304391753-57bca423-49c1-40a6-9a25-9f3e25df5af8.webp",
      ],
    },
  },
];

export const getImagesForDevice = (locationKey, deviceType = "desktop") => {
  const location = facilityLocations.find((loc) => loc.key === locationKey);
  return location ? location.images[deviceType] : [];
};

export const getLocationData = (locationKey) => {
  return facilityLocations.find((loc) => loc.key === locationKey);
};
