// Location-specific pricing data
export const LOCATION_PRICING = {
  "calgary-seton": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$28.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$32.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "calgary-royal-oak": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$29.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$33.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "calgary-sunridge": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$27.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$31.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "edmonton-south": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$26.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$30.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "edmonton-north": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$26.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$30.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "edmonton-downtown": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$27.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$31.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "burnaby-brentwood": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$34.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$38.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
  "vancouver-post": {
    sectionTitle: "Simple Pricing, No Surprises",
    sectionSubtitle:
      "Flexible plans designed to fit your goals and your lifestyle",
    plans: [
      {
        title: "1 Year Contract",
        billing: "Bi-Weekly",
        price: "$36.50",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
      {
        title: "Month To Month",
        billing: "Bi-Weekly",
        price: "$40.99",
        featuresTitle: "Feature you'll like:",
        features: [
          "$0 Enrolment Fee",
          "$0 Maintenance Fee",
          "Personalized Assessment",
          "Access to All Locations",
          "On-Site Health Services",
          "Modern, Clean Facilities",
          "24/7 Online Member Portal",
        ],
        buttonText: "JOIN NOW",
      },
    ],
  },
};

// Default pricing (fallback)
export const DEFAULT_PRICING = {
  sectionTitle: "Simple Pricing, No Surprises",
  sectionSubtitle:
    "Flexible plans designed to fit your goals and your lifestyle",
  plans: [
    {
      title: "1 Year Contract",
      billing: "Bi-Weekly",
      price: "$28.50",
      featuresTitle: "Feature you'll like:",
      features: [
        "$0 Enrolment Fee",
        "$0 Maintenance Fee",
        "Personalized Assessment",
        "Access to All Locations",
        "On-Site Health Services",
        "Modern, Clean Facilities",
        "24/7 Online Member Portal",
      ],
      buttonText: "JOIN NOW",
    },
    {
      title: "Month To Month",
      billing: "Bi-Weekly",
      price: "$32.99",
      featuresTitle: "Feature you'll like:",
      features: [
        "$0 Enrolment Fee",
        "$0 Maintenance Fee",
        "Personalized Assessment",
        "Access to All Locations",
        "On-Site Health Services",
        "Modern, Clean Facilities",
        "24/7 Online Member Portal",
      ],
      buttonText: "JOIN NOW",
    },
  ],
};
